### ISSUE TITLE
AttributeError:  'Xrenner' object has no attribute 'docname'

### ISSUE THREAD

**Issue by flackbash** [amir-zeldes/xrenner#105]
I'm trying to run the example code from the README.
I'm using spacy's dependency parser and manually put it into Conll format.

I get the following error:

```
Traceback (most recent call last):
  File "test.py", line 63, in <module>
    sgml_result = xrenner.analyze(conllx_result, "sgml")
  File "/home/prangen/.local/lib/python3.8/site-packages/xrenner/modules/xrenner_xrenner.py", line 108, in analyze
    infile = self.depedit.run_depedit(infile, self.docname)
AttributeError: 'Xrenner' object has no attribute 'docname'

```

Using the README's example input yields the same error.

Do you have an idea what the problem is?

**Comment by amir-zeldes** [comment]
This is module usage right? Or are you getting that from the command line?

It looks like the docname property isn't being set correctly, which normally gets fed from the name of the file being processed. If the filename has some unusual encoding that could maybe even happen from the cli, but otherwise it's probably just an oversight. The quickest fix is to path that line to set some arbitrary name if it's missing.

**Comment by amir-zeldes** [comment]
It looks like it wasn't being initialized in the constructor, I'm a little surprised this issue never turned up before...

In any case it's fixed in d013484 if you clone from dev you should be good to go.

**Comment by flackbash** [comment]
Thanks for the quick fix. This solves it.

However, I'm running directly into the next error:

```
Traceback (most recent call last):
  File "test.py", line 63, in <module>
    sgml_result = xrenner.analyze("dep_parse.txt", "sgml")
  File "/nfs/students/natalie-prange/src/xrenner/xrenner/modules/xrenner_xrenner.py", line 159, in analyze
    seq_preds = lex.sequencer.predict_proba(s_texts)
  File "/nfs/students/natalie-prange/src/xrenner/xrenner/modules/xrenner_sequence.py", line 226, in predict_proba
    preds = self.tagger.predict(sentences)
  File "/home/prangen/.local/lib/python3.8/site-packages/flair/models/sequence_tagger_model.py", line 364, in predict
    batch = self._filter_empty_sentences(batch)
  File "/home/prangen/.local/lib/python3.8/site-packages/flair/models/sequence_tagger_model.py", line 953, in _filter_empty_sentences
    filtered_sentences = [sentence for sentence in sentences if sentence.tokens]
  File "/home/prangen/.local/lib/python3.8/site-packages/flair/models/sequence_tagger_model.py", line 953, in <listcomp>
    filtered_sentences = [sentence for sentence in sentences if sentence.tokens]
AttributeError: 'str' object has no attribute 'tokens'
```

It seems like a conversion from a list of sentence-strings to a list of flair.data.Sentence is missing.
Adjusting e.g. [this line](https://github.com/amir-zeldes/xrenner/blob/925cf1fdfaecef85a75c0b84065a10a1387aa841/xrenner/modules/xrenner_sequence.py#L223) to

```
    from flair.data import Sentence
    sentences = [Sentence(s[2]) for s in sents]
```

seems to solve the problem.

**Comment by amir-zeldes** [comment]
This one I can't reproduce, it sounds like maybe a version conflict with flair, if they've changed something about their Sentence API. We required `flair>=0.44`, but it's possible we also need to limit to a specific version. What flair version are you running? I'm on 0.4.5 and not getting this error.

**Comment by flackbash** [comment]
Yes, you are right. I'm using flair 0.6. Looks like this change was part of the [0.5.1 release](https://github.com/flairNLP/flair/releases/tag/v0.5.1).

**Comment by amir-zeldes** [comment]
OK, I can add the fixed flair version to requirements and make a new release, if everything is working now. Are there still any problems? Which flair are you using now?

**Comment by flackbash** [comment]
Sorry for the late reply. I made adjustments in the code such that it was working with flair==0.6. However, I just tested it with flair==0.5 without the adjustments and the test snippet is running fine.

I encountered a special case which xrenner can't seem to handle.
I'm processing Wikipedia articles and every now and then there are some unusual space characters mixed in with normal whitespace characters, i.e. a non-breaking space `\xc2\xa0`.
My dependency parser (spaCy parser) tags these as SPACE instead of handling it as a token delimiter:

```
...
5	December	December	PROPN	NNP	NounType=prop|Number=sing	4	pobj	_	SpaceAfter=No
6	 	  	SPACE	_SP	_	5		_	SpaceAfter=No
7	25–26	25–26	NUM	CD	NumType=card	4	pobj	_	SpaceAfter=No
...
```

However, the tokenization [here](https://github.com/amir-zeldes/xrenner/blob/925cf1fdfaecef85a75c0b84065a10a1387aa841/xrenner/modules/xrenner_sequence.py#L236) does not regard them as a token.
This causes a mismatch [here](https://github.com/amir-zeldes/xrenner/blob/925cf1fdfaecef85a75c0b84065a10a1387aa841/xrenner/modules/xrenner_xrenner.py#L188) such that this line throws a list index out of range error.

An additional index out of range error due to the non-breaking space occurs [here](https://github.com/amir-zeldes/xrenner/blob/925cf1fdfaecef85a75c0b84065a10a1387aa841/xrenner/modules/xrenner_xrenner.py#L527) and [here](https://github.com/amir-zeldes/xrenner/blob/925cf1fdfaecef85a75c0b84065a10a1387aa841/xrenner/modules/xrenner_xrenner.py#L536) which I fixed with a preceding `len(first_name_candidate) > 0 and len(last_name_candidate) > 0 `.

I don't know how other dependency parsers handle such whitespaces. However, since spaCy is commonly used, it would be helpful if xrenner could deal with this.

**Comment by amir-zeldes** [comment]
OK, I've frozen the flair version for now, but hopefully the flair API will stabilize in the near future and then it's worth retraining the models and removing the version restriction (presumably in flair 1.0).

For the whitespace issue I'm a little unsure what xrenner can/should do here. The system is fed conll-u dependency parses, so it doesn't really do any tokenization by itself. The whitespace token being ignored seems to be due to flair behavior. If this was just a weird flair bug we could try to replace it with a dummy token so that flair keeps it, or just inject an extra token later since it doesn't really need NER tags added. 

But I think the real problem here is Spacy, for two reasons:
  * The conll-u spec doesn't accept completely empty whitespace tokens (even medial spaces are controversial)
  * Semantically, Spacy has made a tokenization error here, so if we wanted to hardwire a fix, it should ideally happen before the dependency parse (which is outside xrenner)

My honest recommendation would be to either do a simple replace of nbsp > space before doing anything, or to just use Stanza, which I find more reliable than Spacy. Fixing something like tokenization this late in the NLP pipeline seems like it's not the best choice IMO. Thanks for reporting either way!

**Comment by flackbash** [comment]
Great, thanks for the flair-fix!

About the whitespace issue - I agree with you that this is not really a problem of xrenner and can live with fixing this at another point in the pipeline. Thanks for the clarifications.

**Comment by amir-zeldes** [comment]
OK, thanks again for reporting the issue!
